codecov:
  notify:
    require_ci_to_pass: yes
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "70...90"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: "app"
        type: "project"
        carryforward_behavior: "exclude"
        flag_coverage_not_uploaded_behavior: "exclude"
  individual_flags:
    - name: unit
      carryforward: false


comment:
  layout: "header, diff, flags"
  behavior: default
  require_changes: no
  require_base: no