name: core team workflow

on:
  push:
    branches:
      - 'core/**'

jobs:
  core-app:
    runs-on: ubuntu-latest
    name: Test Core App
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: python -m pytest core/** --cov=./core --cov-report=xml:core/unit.coverage.xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
        flags: core