name: fruit team workflow

on:
  push:
    branches:
      - 'fruits/**'

jobs:
  fruits-app:
    runs-on: ubuntu-latest
    name: Test Fruits App
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: python -m pytest fruits/** --cov=./fruits --cov-report=xml:fruits/unit.coverage.xml
    - name: Download CLI release
      run: |
        mkdir /tmp/cli
        curl --fail --output /tmp/cli/codecovcli https://cli.codecov.io/v0.1.2/linux/codecov
        chmod +x /tmp/cli/codecovcli
    - name: Upload coverage to codecov using CLI
      run: |
        /tmp/cli/codecovcli --verbose do-upload --legacy --flag fruits --token=${{ secrets.CODECOV_TOKEN }} --fail-on-error
    - name: Also upload to staging
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_STAGING_TOKEN }} # not required for public repos
        url: https://stage-api.codecov.dev
        flags: staging-fruits
        fail_ci_if_error: true
        verbose: true