name: smart test selection

on: [push]

jobs:
  install-codecov-cli:
    uses: ./.github/workflows/download_cli.yml
  static-analysis:
    needs: install-codecov-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"
      - name: Get the Codecov CLI binary
        uses: actions/download-artifact@v2
        with:
          name: codecov-cli-binary
      - name: Fix binary permission
        run: |
          chmod +x codecov
      - name: Save commit info 
        run: |
          ./codecov create-commit --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
      - name: Create report
        run: |
          ./codecov create-report --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
      - name: Run Static Analysis
        run: |
          ./codecov static-analysis --token=${{ secrets.STATIC_TOKEN }}
  iterative-testing:
    needs: static-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"
      - name: Install Pytest and its dependencies
        run: |
          pip install pytest pytest-cov pytest-mock
      - name: Get the Codecov CLI binary
        uses: actions/download-artifact@v2
        with:
          name: codecov-cli-binary
      - name: Fix binary permission
        run: |
          chmod +x codecov
      - name: Run smart test selection
        run: |
          BASE_COMMIT=$(git merge-base ${{ github.sha }}^ origin/main)
          echo "Using base commit ${BASE_COMMIT}"
          ./codecov label-analysis --token=${{ secrets.STATIC_TOKEN }} --base-sha=${BASE_COMMIT}
          coverage json --show-contexts -o label.coverage.json
          rm .coverage
          ./codecov --verbose do-upload --flag smart-tests --file=label.coverage.json --token=${{ secrets.CODECOV_TOKEN }}  --fail-on-error
