name: smart test selection

on: [push]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"
      - name: Download CLI release
        run: |
          mkdir /tmp/cli
          curl --fail --output /tmp/cli/codecovcli https://cli.codecov.io/v0.1.2/linux/codecov
          chmod +x /tmp/cli/codecovcli
      - name: Save commit info 
        run: |
          /tmp/cli/codecovcli create-commit --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
      - name: Create report
        run: |
          /tmp/cli/codecovcli create-report --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
      - name: Run Static Analysis
        run: |
          /tmp/cli/codecovcli static-analysis --token=${{ secrets.STATIC_TOKEN }}
  iterative-testing:
    needs: static-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download CLI release
        run: |
          mkdir /tmp/cli
          curl --fail --output /tmp/cli/codecovcli https://cli.codecov.io/v0.1.2/linux/codecov
          chmod +x /tmp/cli/codecovcli
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"
      - name: Install Pytest and its dependencies
        run: |
          pip install pytest pytest-cov pytest-mock
      - name: Run smart test selection
        run: |
          BASE_COMMIT=$(git merge-base ${{ github.sha }}^ origin/main)
          echo "Using base commit ${BASE_COMMIT}"
          /tmp/cli/codecovcli label-analysis --token=${{ secrets.STATIC_TOKEN }} --base-sha=${BASE_COMMIT}
          coverage json --show-contexts -o label.coverage.json
          /tmp/cli/codecovcli do-upload --flag smart-tests --file=label.coverage.json --token=${{ secrets.CODECOV_TOKEN }}
