name: Staging

on:
  push:
    branches:
      - main

jobs:
  codecov-startup:
    runs-on: ubuntu-latest
    name: Startup Codecov Info
    steps:
    - name: Download CLI release
      run: |
        mkdir /tmp/cli
        curl --fail --output /tmp/cli/codecovcli https://cli.codecov.io/v0.1.2/linux/codecov
        chmod +x /tmp/cli/codecovcli
    - name: Save commit info 
      run: |
        /tmp/cli/codecovcli create-commit --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
    - name: Create report
      run: |
        /tmp/cli/codecovcli create-report --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
  build-and-test:
    needs: codecov-startup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: core
            REPORT_PATH: core/unit.coverage.xml
          - app: fruits
            REPORT_PATH: emotions/unit.coverage.xml
          - app: emotions
            REPORT_PATH: fruits/unit.coverage.xml
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: python -m pytest ${{ matrix.app }}/** --cov=./${{ matrix.app }} --cov-report=xml:${{ matrix.REPORT_PATH }}
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_STAGING_TOKEN }} # not required for public repos
        url: https://stage-api.codecov.dev
        flags: staging
        fail_ci_if_error: true
        verbose: true